### ISSUE TITLE
Authorizer function not invoked

### ISSUE THREAD

**Issue by CeccoCQ** [Willis0826/sam-local-authorizer-example#1]
Hello,

Regarding: https://github.com/aws/aws-sam-cli/issues/137#issuecomment-1742574583

In your code, if you add a `console.log` statement into:

```javascript
export const lambdaHandler: APIGatewayTokenAuthorizerHandler = async (event, context) => {
  console.log("Hello auth");
  return generateAdminPolicy(event);
};
```
This log is never printed.
If you don't send the "Authorization" header, it's okay because the Gateway stops the request.

**Comment by Willis0826** [comment]
Hey, I assume you are running `sam build && sam local start-api` command in the `http-apis` folder. I can get the `Hello auth` output as the screenshots below. 

![Screenshot 2023-10-02 200408](https://github.com/Willis0826/sam-local-authorizer-example/assets/10431078/e94af78e-f687-4fcc-acd3-d25209641ceb)
![Screenshot 2023-10-02 200918](https://github.com/Willis0826/sam-local-authorizer-example/assets/10431078/87041dba-e117-457f-9e1e-0e34204240ed)

What is your SAM CLI version? Mine is `1.94.0`

**Comment by CeccoCQ** [comment]
Hi @Willis0826, it seems I overlooked the "sam build" command.
Your code works perfectly, but mine doesn't—I'll investigate further.

On another note, have you tried debugging with VSCode by adding a breakpoint to the auth function and the pong lambda?
For instance, if I pass a Bearer token in JWT format to the auth function and want to check its validity through debugging, do you think that's possible?

**Comment by Willis0826** [comment]
Ah, please feel free to let me know if you need any help with your SAM project.

I tried the VSCode debugger and AWS SAM stuff today, but I couldn't make it work. I also found out you have an open issue https://github.com/aws/aws-sam-cli/issues/3749 

The issue I faced is that I can not expose the debug port with `sam local start-api -d 5858`

**Comment by Willis0826** [comment]
Hey, I will close this issue for now. But please feel free to re-open this issue, if you would like me help with the SAM config.
